apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.jwks.namespace }}"
  name: jwks
  labels:
    service: jwks
    release: "jwks"
    app: jwks
spec:
  ports:
  - port: 80
    targetPort: http
    name: http
  selector:
    service: jwks
  type: ClusterIP
